import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {LayoutDashboard,Building2,Users,Ticket,WalletCards,ShieldCheck,Search,LogOut,KeyRound,AlertCircle,Check,X,Trash2,MessageCircle} from 'lucide-react'
import './styles.css'
import {supabase,isSupabaseConfigured} from './supabase'

function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const submit=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)};return <div className="admin-login"><form onSubmit={submit}><div className="brand">pari<span>.</span><small>ADMIN</small></div><h1>Control Center</h1>{!isSupabaseConfigured&&<p className="err">Faltan variables ENV.</p>}<input type="email" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="err"><AlertCircle/>{error}</p>}<button><KeyRound/>Entrar</button></form></div>}

function Admin({session}){
 const [tab,setTab]=useState('Dashboard');const [profile,setProfile]=useState(null);const [venues,setVenues]=useState([]);const [events,setEvents]=useState([]);const [users,setUsers]=useState([]);const [reservations,setReservations]=useState([]);const [orders,setOrders]=useState([]);const [posts,setPosts]=useState([]);const [loading,setLoading]=useState(true);const [q,setQ]=useState('')
 const load=async()=>{setLoading(true);const {data:p}=await supabase.from('pari_profiles').select('*').eq('id',session.user.id).maybeSingle();setProfile(p||null);if(p?.role!=='admin'){setLoading(false);return}const [{data:v},{data:e},{data:u},{data:r},{data:o},{data:w}]=await Promise.all([
  supabase.from('pari_venues').select('*').order('name'),supabase.from('pari_events').select('*').order('starts_at',{ascending:false}),supabase.from('pari_profiles').select('*').order('created_at',{ascending:false}),supabase.from('pari_reservations').select('*,pari_venues(name)').order('created_at',{ascending:false}),supabase.from('pari_ticket_orders').select('*,pari_events(title)').order('created_at',{ascending:false}),supabase.from('pari_wall_posts').select('*').order('created_at',{ascending:false})]);setVenues(v||[]);setEvents(e||[]);setUsers(u||[]);setReservations(r||[]);setOrders(o||[]);setPosts(w||[]);setLoading(false)}
 useEffect(()=>{load()},[session.user.id])
 const toggleVenue=async(v,field)=>{const {data}=await supabase.from('pari_venues').update({[field]:!v[field]}).eq('id',v.id).select().single();setVenues(x=>x.map(i=>i.id===v.id?data:i))}
 const changeEvent=async(e,status)=>{const {data}=await supabase.from('pari_events').update({status}).eq('id',e.id).select().single();setEvents(x=>x.map(i=>i.id===e.id?data:i))}
 const deletePost=async id=>{await supabase.from('pari_wall_posts').delete().eq('id',id);setPosts(x=>x.filter(p=>p.id!==id))}
 if(loading)return <div className="loading-admin">Cargando Pari Admin…</div>
 if(profile?.role!=='admin')return <div className="admin-login"><div className="no-access"><ShieldCheck/><h1>Sin acceso administrativo</h1><p>La cuenta {session.user.email} no tiene role = admin en pari_profiles.</p><button onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></div></div>
 const nav=[[LayoutDashboard,'Dashboard'],[Building2,'Negocios'],[Users,'Usuarios'],[Ticket,'Eventos'],[WalletCards,'Reservaciones'],[MessageCircle,'Muro'],[ShieldCheck,'Moderación']]
 const term=q.toLowerCase()
 return <div className="wrap"><aside><div className="brand">pari<span>.</span><small>ADMIN</small></div>{nav.map(([I,t])=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><I/>{t}</button>)}<button className="admin-out" onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></aside><main><header><div><p>PARI CONTROL CENTER · SUPABASE</p><h1>{tab}</h1></div><div className="search"><Search/><input placeholder="Buscar..." value={q} onChange={e=>setQ(e.target.value)}/></div></header>
 {tab==='Dashboard'&&<><div className="kpis"><article><span>Negocios</span><b>{venues.length}</b></article><article><span>Usuarios</span><b>{users.length}</b></article><article><span>Eventos</span><b>{events.length}</b></article><article><span>Reservaciones</span><b>{reservations.length}</b></article></div><section><h2>Actividad reciente</h2><p>{orders.length} órdenes de boletos · {posts.length} publicaciones en muro · {reservations.filter(r=>r.status==='pending').length} reservas pendientes.</p></section></>}
 {tab==='Negocios'&&<section><h2>Negocios</h2><table><thead><tr><th>Nombre</th><th>Ciudad</th><th>Activo</th><th>Verificado</th><th>Reservas</th></tr></thead><tbody>{venues.filter(v=>(v.name+v.city).toLowerCase().includes(term)).map(v=><tr key={v.id}><td>{v.name}</td><td>{v.city}</td><td><button className="mini" onClick={()=>toggleVenue(v,'is_active')}>{v.is_active?<Check/>:<X/>}</button></td><td><button className="mini" onClick={()=>toggleVenue(v,'is_verified')}>{v.is_verified?<Check/>:<X/>}</button></td><td>{v.auto_accept_reservations?'Automáticas':'Manuales'}</td></tr>)}</tbody></table></section>}
 {tab==='Usuarios'&&<section><h2>Usuarios</h2><table><thead><tr><th>Nombre</th><th>Correo</th><th>Teléfono</th><th>Rol</th></tr></thead><tbody>{users.filter(u=>((u.full_name||'')+(u.email||'')).toLowerCase().includes(term)).map(u=><tr key={u.id}><td>{u.full_name||'—'}</td><td>{u.email}</td><td>{u.phone||'—'}</td><td>{u.role}</td></tr>)}</tbody></table></section>}
 {tab==='Eventos'&&<section><h2>Eventos</h2><table><thead><tr><th>Evento</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{events.filter(e=>(e.title||'').toLowerCase().includes(term)).map(e=><tr key={e.id}><td>{e.title}</td><td>{new Date(e.starts_at).toLocaleString('es-MX')}</td><td>{e.status}</td><td><div className="actions"><button onClick={()=>changeEvent(e,'published')}><Check/></button><button onClick={()=>changeEvent(e,'cancelled')}><X/></button></div></td></tr>)}</tbody></table></section>}
 {tab==='Reservaciones'&&<section><h2>Reservaciones</h2><table><thead><tr><th>Negocio</th><th>Personas</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id}><td>{r.pari_venues?.name||'—'}</td><td>{r.party_size}</td><td>{r.reservation_date}</td><td>{r.status}</td></tr>)}</tbody></table><h2 style={{marginTop:30}}>Órdenes de boletos</h2><table><thead><tr><th>Evento</th><th>Cantidad</th><th>Total</th><th>Estado</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.pari_events?.title||'—'}</td><td>{o.quantity}</td><td>${Number(o.total).toLocaleString('es-MX')}</td><td>{o.status}</td></tr>)}</tbody></table></section>}
 {tab==='Muro'&&<section><h2>Publicaciones</h2>{posts.map(p=><div className="post-row" key={p.id}><div><b>{p.user_id.slice(0,8)}</b><span>{p.content}</span></div><button onClick={()=>deletePost(p.id)}><Trash2/></button></div>)}</section>}
 {tab==='Moderación'&&<section><h2>Moderación</h2><p>Desde aquí puedes desactivar negocios, cancelar eventos y borrar publicaciones desde sus secciones correspondientes.</p><div className="kpis"><article><span>Negocios inactivos</span><b>{venues.filter(v=>!v.is_active).length}</b></article><article><span>Eventos cancelados</span><b>{events.filter(e=>e.status==='cancelled').length}</b></article><article><span>Posts</span><b>{posts.length}</b></article></div></section>}
 </main></div>
}
function App(){const [session,setSession]=useState(null);const [ready,setReady]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(!ready)return <div className="loading-admin">Cargando…</div>;return session?<Admin session={session}/>:<Login/>}
createRoot(document.getElementById('root')).render(<App/>)
