import React,{useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Home,Compass,CalendarDays,User,Search,MapPin,ChevronRight,Heart,Share2,Clock,Users,Ticket,ChevronLeft,CheckCircle2,Navigation,Music2,Sparkles,MessageCircle,Plus,Image as ImageIcon,Map,Calendar,Phone,Tag,Send,PartyPopper} from 'lucide-react'
import './styles.css'

const venues=[
 {id:'annua',name:'Annua',area:'CDMX',distance:'2.1 km',music:'House · Open format',tag:'Popular',image:'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?auto=format&fit=crop&w=1000&q=80',description:'Una experiencia nocturna de música, diseño y coctelería para empezar tarde y terminar todavía más tarde.',promo:'Cumpleañero + 4 amigos: acceso preferente antes de las 11:30 PM.'},
 {id:'faunna',name:'Faunna',area:'CDMX',distance:'2.8 km',music:'Reggaetón · Hits',tag:'Hoy',image:'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',description:'Noches de reggaetón, hits y ambiente intenso con una producción visual que cambia cada fin de semana.',promo:'Reserva anticipada y recibe acceso prioritario para tu grupo.'},
 {id:'janis',name:'Janis',area:'CDMX',distance:'3.4 km',music:'Open format · House',tag:'Trending',image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80',description:'Open format, house y noches temáticas en un espacio pensado para grupos y celebraciones.',promo:'Entrada preferente antes de medianoche en reservaciones confirmadas.'},
 {id:'mezontle',name:'Mezontle',area:'CDMX',distance:'4.1 km',music:'Reggaetón · Electronic',tag:'Últimos lugares',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=80',description:'Una mezcla de electrónica y reggaetón con noches temáticas, invitados y sets especiales.',promo:'Lista especial disponible en eventos seleccionados.'}
]
const events=[
 {id:1,venueId:'annua',venue:'Annua',title:'Saturday Ritual',date:'Vie 11 Sep',fullDate:'2026-09-11',time:'10:30 PM',price:'Reservaciones abiertas',image:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1000&q=80'},
 {id:2,venueId:'faunna',venue:'Faunna',title:'After Hours',date:'Sáb 12 Sep',fullDate:'2026-09-12',time:'10:00 PM',price:'Lista disponible',image:'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80'},
 {id:3,venueId:'janis',venue:'Janis',title:'Noche 00s',date:'Sáb 12 Sep',fullDate:'2026-09-12',time:'9:30 PM',price:'Reserva tu lugar',image:'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1000&q=80'},
 {id:4,venueId:'mezontle',venue:'Mezontle',title:'Neón',date:'Vie 18 Sep',fullDate:'2026-09-18',time:'11:00 PM',price:'Reservaciones abiertas',image:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80'}
]
const initialPosts=[
 {id:1,user:'Fer',place:'Faunna',time:'Hace 18 min',text:'¿Quién cae hoy? Se está armando buen plan 🔥',likes:28,comments:6,image:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80'},
 {id:2,user:'Vale',place:'Annua',time:'Hace 42 min',text:'El set de anoche estuvo increíble. Repetimos el viernes.',likes:51,comments:9,image:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1000&q=80'},
 {id:3,user:'Diego',place:'Janis',time:'Hace 1 h',text:'Buscando plan para 6 este sábado, ¿quién se apunta?',likes:17,comments:12,image:null}
]
const tabs=[['home','Inicio',Home],['explore','Explorar',Compass],['wall','Muro',MessageCircle],['plans','Planes',CalendarDays],['profile','Perfil',User]]

function App(){
 const [tab,setTab]=useState('home'); const [selected,setSelected]=useState(null); const [selectedEvent,setSelectedEvent]=useState(null); const [liked,setLiked]=useState([])
 const title=tab==='home'?'Pari':tab==='explore'?'Explorar':tab==='wall'?'Muro':tab==='plans'?'Mis planes':'Perfil'
 const openVenue=v=>setSelected(v)
 if(selected) return <Venue venue={selected} onBack={()=>setSelected(null)} liked={liked.includes(selected.id)} toggleLike={()=>setLiked(x=>x.includes(selected.id)?x.filter(i=>i!==selected.id):[...x,selected.id])} initialEvent={selectedEvent} clearEvent={()=>setSelectedEvent(null)} />
 return <div className="app-shell"><main className="screen">
   <header className="topbar"><div><p className="eyebrow">CDMX · ESTA NOCHE</p><h1>{title}</h1></div><button className="avatar">SR</button></header>
   {tab==='home'&&<HomeView openVenue={openVenue} openEvent={e=>{setSelectedEvent(e);openVenue(venues.find(v=>v.id===e.venueId))}}/>}
   {tab==='explore'&&<ExploreView openVenue={openVenue} openEvent={e=>{setSelectedEvent(e);openVenue(venues.find(v=>v.id===e.venueId))}}/>}
   {tab==='wall'&&<WallView/>}
   {tab==='plans'&&<PlansView setTab={setTab}/>} 
   {tab==='profile'&&<ProfileView/>}
 </main><Nav tab={tab} setTab={setTab}/></div>
}

function HomeView({openVenue,openEvent}){return <>
 <section className="hero"><div className="hero-copy"><span className="pill glow"><Sparkles size={13}/> Esta noche en CDMX</span><h2>Tu noche empieza<br/>aquí.</h2><p>Descubre lugares, eventos y planes para hoy.</p><button onClick={()=>document.getElementById('popular')?.scrollIntoView({behavior:'smooth'})}>Explorar ahora <ChevronRight size={17}/></button></div></section>
 <Section title="Lo más caliente" subtitle="Eventos que todos están guardando"><div className="event-scroll">{events.map(e=><EventCard key={e.id} e={e} onClick={()=>openEvent(e)}/>)}</div></Section>
 <Section id="popular" title="Lugares populares" subtitle="Antros que están moviendo la noche"><div className="venue-grid">{venues.map(v=><VenueCard key={v.id} v={v} onClick={()=>openVenue(v)}/>)}</div></Section>
 <div className="spacer"/>
</>}

function ExploreView({openVenue,openEvent}){
 const [q,setQ]=useState(''); const [mode,setMode]=useState('venues'); const [showMap,setShowMap]=useState(false); const [showCreate,setShowCreate]=useState(false)
 const filteredVenues=useMemo(()=>venues.filter(v=>(v.name+v.area+v.music).toLowerCase().includes(q.toLowerCase())),[q])
 const filteredEvents=useMemo(()=>events.filter(e=>(e.title+e.venue+e.date).toLowerCase().includes(q.toLowerCase())),[q])
 if(showMap) return <MapView openVenue={openVenue} onBack={()=>setShowMap(false)}/>
 if(showCreate) return <CreateEvent onBack={()=>setShowCreate(false)}/>
 return <>
   <div className="explore-switch"><button className={mode==='venues'?'active':''} onClick={()=>setMode('venues')}>Antros</button><button className={mode==='events'?'active':''} onClick={()=>setMode('events')}>Eventos</button></div>
   <button className="map-cta" onClick={()=>setShowMap(true)}><div><Map size={19}/><span><b>Ver mapa</b><small>Explora qué hay cerca de ti</small></span></div><ChevronRight/></button>
   <div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={mode==='venues'?'Buscar antro o zona':'Buscar evento o antro'}/></div>
   {mode==='venues'?<><div className="chips">{['Todos','Popular','Hoy','Cerca','Últimos lugares'].map(x=><button key={x}>{x}</button>)}</div><div className="explore-list">{filteredVenues.map(v=><button className="explore-card" key={v.id} onClick={()=>openVenue(v)}><img src={v.image}/><div className="shade"/><span className="tag">{v.tag}</span><div className="card-copy"><h3>{v.name}</h3><p><MapPin size={14}/>{v.area} · {v.distance}</p><small>{v.music}</small></div><ChevronRight className="arrow"/></button>)}</div></>:
   <><button className="create-event-card" onClick={()=>setShowCreate(true)}><div className="create-icon"><Plus/></div><div><b>Crear un evento</b><span>¿Organizas una fiesta o evento? Publícalo en Pari.</span></div><ChevronRight/></button><div className="event-list">{filteredEvents.map(e=><button className="event-list-card" key={e.id} onClick={()=>openEvent(e)}><img src={e.image}/><div><span>{e.date}</span><h3>{e.title}</h3><p>{e.venue} · {e.time}</p><small>{e.price}</small></div><ChevronRight/></button>)}</div></>}
   <div className="spacer"/>
 </>
}

function MapView({openVenue,onBack}){return <div className="subpage"><div className="subpage-head"><button className="circle" onClick={onBack}><ChevronLeft/></button><div><p className="eyebrow">EXPLORAR</p><h1>Mapa</h1></div></div><div className="mapbox"><div className="map-noise"></div>{venues.map((v,i)=><button className={'pin p'+i} key={v.id} onClick={()=>openVenue(v)}><MapPin size={16}/><span>{v.name}</span></button>)}<button className="locate"><Navigation size={17}/></button></div><Section title="Cerca de ti" subtitle="Con actividad esta noche"><div className="mini-list">{venues.slice(0,3).map(v=><VenueRow v={v} key={v.id} onClick={()=>openVenue(v)}/>)}</div></Section></div>}

function CreateEvent({onBack}){const [date,setDate]=useState('');const [phone,setPhone]=useState('');const [sent,setSent]=useState(false);if(sent)return <div className="subpage create-success"><CheckCircle2/><h1>Recibimos tu evento</h1><p>El equipo de Pari te contactará al número <b>{phone}</b> para revisar los detalles y ayudarte a publicarlo.</p><button className="primary" onClick={onBack}>Volver a eventos</button></div>;return <div className="subpage"><div className="subpage-head"><button className="circle" onClick={onBack}><ChevronLeft/></button><div><p className="eyebrow">EVENTOS</p><h1>Crear un evento</h1></div></div><div className="form-card"><PartyPopper/><h2>Cuéntanos cuándo será</h2><p>Por ahora Pari revisará cada evento antes de publicarlo.</p><label>Fecha del evento<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Tu número de WhatsApp<input type="tel" placeholder="55 1234 5678" value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="primary" disabled={!date||phone.length<8} onClick={()=>setSent(true)}>Enviar solicitud <Send size={17}/></button><small>Al enviar, aceptas que el equipo de Pari te contacte para completar la publicación.</small></div></div>}

function WallView(){const [posts,setPosts]=useState(initialPosts);const [composer,setComposer]=useState(false);const [text,setText]=useState('');const [liked,setLiked]=useState([]);const [openComments,setOpenComments]=useState([]);const publish=()=>{if(!text.trim())return;setPosts([{id:Date.now(),user:'Santiago',place:'CDMX',time:'Ahora',text:text.trim(),likes:0,comments:0,image:null},...posts]);setText('');setComposer(false)};return <>
 <button className="wall-compose" onClick={()=>setComposer(!composer)}><div className="small-avatar">SR</div><span>Comparte el plan...</span><ImageIcon/></button>
 {composer&&<div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="¿Qué está pasando esta noche?" autoFocus/><div><button onClick={()=>setComposer(false)}>Cancelar</button><button className="primary" onClick={publish}>Publicar</button></div></div>}
 <div className="feed">{posts.map(p=><article className="post" key={p.id}><header><div className="post-avatar">{p.user[0]}</div><div><b>{p.user}</b><span><MapPin size={12}/>{p.place} · {p.time}</span></div></header><p>{p.text}</p>{p.image&&<img src={p.image}/>}<div className="post-stats"><span>{p.likes+(liked.includes(p.id)?1:0)} Me gusta</span><span>{p.comments} comentarios</span></div><div className="post-actions"><button className={liked.includes(p.id)?'liked':''} onClick={()=>setLiked(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/> Me gusta</button><button onClick={()=>setOpenComments(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}><MessageCircle/> Comentar</button></div>{openComments.includes(p.id)&&<div className="comments"><div><b>Mariana</b><span>¿A qué hora llegan?</span></div><div><b>Alex</b><span>Yo jalo 🔥</span></div><div className="comment-box"><input placeholder="Escribe un comentario..."/><button><Send/></button></div></div>}</article>)}</div><div className="spacer"/>
 </>}

function PlansView({setTab}){return <><div className="empty-hero"><Ticket size={38}/><h2>Tus próximas noches</h2><p>Cuando reserves o te registres a un evento, aparecerá aquí.</p><button onClick={()=>setTab('explore')}>Explorar eventos</button></div><Section title="Guardados"><div className="saved-placeholder"><Heart/><span>Aún no guardas eventos</span></div></Section></>}
function ProfileView(){return <><div className="profile-card"><div className="big-avatar">SR</div><div><h2>Santiago</h2><p>Miembro de Pari</p></div></div><div className="settings">{['Mis reservaciones','Notificaciones','Mis favoritos','Invitar amigos','Ayuda y soporte'].map(x=><button key={x}><span>{x}</span><ChevronRight/></button>)}</div></>}

function Venue({venue,onBack,liked,toggleLike,initialEvent,clearEvent}){const [showBook,setShowBook]=useState(false);const [eventForBooking,setEventForBooking]=useState(initialEvent||null);const venueEvents=events.filter(e=>e.venueId===venue.id);if(showBook)return <Booking venue={venue} event={eventForBooking} onBack={()=>{setShowBook(false);setEventForBooking(null);clearEvent?.()}}/>;return <div className="app-shell"><main className="screen venue-screen"><div className="venue-hero" style={{backgroundImage:`url(${venue.image})`}}><div className="venue-gradient"/><button className="circle back" onClick={onBack}><ChevronLeft/></button><div className="hero-actions"><button className="circle" onClick={toggleLike}><Heart fill={liked?'currentColor':'none'}/></button><button className="circle"><Share2/></button></div><div className="venue-title"><span className="pill">{venue.tag}</span><h1>{venue.name}</h1><p><MapPin size={15}/>{venue.area} · {venue.distance}</p></div></div><div className="venue-body"><div className="quickfacts"><span><Clock/>10:00 PM – 3:00 AM</span><span><Music2/>{venue.music}</span></div><h2>Sobre {venue.name}</h2><p className="venue-description">{venue.description}</p><div className="gallery"><img src={venue.image}/><img src="https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=700&q=80"/><img src="https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=700&q=80"/></div><h2>Promociones</h2><div className="promo-card"><Tag/><div><b>Beneficio Pari</b><span>{venue.promo}</span></div></div><h2>Próximos eventos</h2>{venueEvents.length?<div className="venue-events">{venueEvents.map(e=><div className="venue-event" key={e.id}><img src={e.image}/><div><span>{e.date}</span><h3>{e.title}</h3><p>{e.time}</p></div><button onClick={()=>{setEventForBooking(e);setShowBook(true)}}>Reservar</button></div>)}</div>:<p className="muted">Todavía no hay eventos publicados.</p>}<div className="venue-info"><div><MapPin/><span><b>Ubicación</b><small>CDMX · Ver cómo llegar</small></span></div><div><Clock/><span><b>Horario</b><small>Jue–Sáb · 10:00 PM a 3:00 AM</small></span></div><div><Users/><span><b>Edad</b><small>Acceso para mayores de 18 años</small></span></div></div><div className="spacer"/></div></main><div className="bookbar"><div><small>¿Quieres ir a {venue.name}?</small><b>Reserva tu lugar</b></div><button onClick={()=>{setEventForBooking(null);setShowBook(true)}}>Reservar</button></div></div>}

function Booking({venue,event,onBack}){const [step,setStep]=useState(1);const [people,setPeople]=useState(4);const [date,setDate]=useState(event?.fullDate||'2026-09-12');const [time,setTime]=useState(event?.time||'11:00 PM');const [done,setDone]=useState(false);if(done)return <div className="app-shell"><main className="screen success"><CheckCircle2/><p className="eyebrow">SOLICITUD ENVIADA</p><h1>Reservación en {venue.name}</h1><p>Tu solicitud para {people} {people===1?'persona':'personas'} quedó registrada. Te avisaremos cuando el lugar la confirme.</p><div className="qr">▦</div><div className="confirmation">{event&&<span>{event.title}</span>}<b>{formatDate(date)} · {time}</b><span>{people} {people===1?'persona':'personas'}</span><small>Reserva #PARI-09261</small></div><button className="primary" onClick={()=>location.reload()}>Ver mis planes</button></main></div>;
 return <div className="app-shell"><main className="screen booking"><header className="booking-head"><button className="circle" onClick={onBack}><ChevronLeft/></button><div><p className="eyebrow">RESERVAR EN</p><h1>{venue.name}</h1>{event&&<small>{event.title}</small>}</div><span>{step}/2</span></header><div className="progress"><i style={{width:(step/2*100)+'%'}}/></div>{step===1&&<div className="step"><h2>Arma tu reservación</h2><p>Selecciona para cuántas personas y qué día quieres ir.</p><label className="date-field"><Calendar/><span>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></span></label><div className="counter"><button onClick={()=>setPeople(Math.max(1,people-1))}>−</button><strong>{people}</strong><button onClick={()=>setPeople(Math.min(20,people+1))}>+</button></div><p className="counter-label">{people===1?'1 persona':`${people} personas`}</p><div className="people-presets">{[2,4,6,8,10].map(n=><button key={n} onClick={()=>setPeople(n)} className={people===n?'selected':''}>{n} personas</button>)}</div><h3 className="time-title">Hora estimada de llegada</h3><div className="time-options">{['10:00 PM','10:30 PM','11:00 PM','11:30 PM','12:00 AM'].map(t=><button key={t} className={time===t?'selected':''} onClick={()=>setTime(t)}>{t}</button>)}</div></div>}{step===2&&<div className="step"><h2>Confirma tu reservación</h2><p>El lugar recibirá tu solicitud con estos datos.</p><div className="reservation-card"><Users/><div><small>Grupo</small><strong>{people} {people===1?'persona':'personas'}</strong></div></div><div className="summary-card"><span>Lugar</span><b>{venue.name}</b>{event&&<><span>Evento</span><b>{event.title}</b></>}<span>Fecha</span><b>{formatDate(date)}</b><span>Hora</span><b>{time}</b></div><p className="muted">La reservación queda pendiente hasta que {venue.name} la confirme.</p></div>}<div className="booking-bottom"><button className="primary" onClick={()=>step<2?setStep(2):setDone(true)}>{step<2?'Revisar reservación':'Enviar reservación'} <ChevronRight size={18}/></button></div></main></div>}

function formatDate(date){if(!date)return 'Fecha por definir';const d=new Date(date+'T12:00:00');return d.toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'})}
function Section({title,subtitle,children,id}){return <section className="section" id={id}><div className="section-head"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>}
function EventCard({e,onClick}){return <button className="event-card" onClick={onClick}><img src={e.image}/><div className="event-overlay"/><span className="event-date">{e.date}</span><div><small>{e.venue}</small><h3>{e.title}</h3><p>{e.time} · {e.price}</p></div></button>}
function VenueCard({v,onClick}){return <button className="venue-card" onClick={onClick}><img src={v.image}/><div><span className="venue-tag">{v.tag}</span><h3>{v.name}</h3><p><MapPin size={13}/>{v.area}</p><small>{v.music}</small></div></button>}
function VenueRow({v,onClick}){return <button className="venue-row" onClick={onClick}><img src={v.image}/><div><b>{v.name}</b><span>{v.area} · {v.distance}</span><small>{v.music}</small></div><ChevronRight/></button>}
function Nav({tab,setTab}){return <nav className="bottom-nav">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>}
createRoot(document.getElementById('root')).render(<App/>)
