import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {CalendarDays,Users,ScanLine,BarChart3,Settings,Plus,LogOut,Building2,KeyRound,AlertCircle,Image,Save,Check,X,Upload,Trash2,ToggleLeft,ToggleRight,PartyPopper} from 'lucide-react'
import './styles.css'
import {supabase,isSupabaseConfigured} from './supabase'

function Login(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 const submit=async e=>{e.preventDefault();if(!supabase)return;setLoading(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setLoading(false)}
 return <div className="login-page"><form className="login-card" onSubmit={submit}><div className="brand">pari<span>.</span><small>NEGOCIOS</small></div><h1>Panel de negocios</h1><p>Entra con la cuenta asignada a tu antro.</p>{!isSupabaseConfigured&&<div className="login-error"><AlertCircle/>Faltan variables de Supabase.</div>}<label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error"><AlertCircle/>{error}</div>}<button className="login-button" disabled={loading||!isSupabaseConfigured}><KeyRound/>{loading?'Entrando…':'Entrar'}</button></form></div>
}

function Dashboard({session}){
 const [tab,setTab]=useState('Resumen');const [venue,setVenue]=useState(null);const [membership,setMembership]=useState(null);const [reservations,setReservations]=useState([]);const [events,setEvents]=useState([]);const [photos,setPhotos]=useState([]);const [promos,setPromos]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [edit,setEdit]=useState({});const [newEvent,setNewEvent]=useState({title:'',starts_at:'',description:''});const [newPromo,setNewPromo]=useState({title:'',description:''});
 const load=async()=>{setLoading(true);setError('');const {data:member,error:memberError}=await supabase.from('pari_venue_members').select('id,role,venue_id,pari_venues(*)').eq('user_id',session.user.id).maybeSingle();if(memberError||!member){setError(memberError?.message||'Esta cuenta no está asignada a un negocio.');setLoading(false);return}setMembership(member);setVenue(member.pari_venues);setEdit(member.pari_venues);const [{data:r},{data:e},{data:p},{data:pr}]=await Promise.all([
  supabase.from('pari_reservations').select('*').eq('venue_id',member.venue_id).order('created_at',{ascending:false}),
  supabase.from('pari_events').select('*').eq('venue_id',member.venue_id).order('starts_at',{ascending:true}),
  supabase.from('pari_venue_photos').select('*').eq('venue_id',member.venue_id).order('position'),
  supabase.from('pari_venue_promotions').select('*').eq('venue_id',member.venue_id).order('created_at',{ascending:false})
 ]);setReservations(r||[]);setEvents(e||[]);setPhotos(p||[]);setPromos(pr||[]);setLoading(false)}
 useEffect(()=>{load()},[session.user.id])
 const today=new Date().toISOString().slice(0,10);const todayReservations=useMemo(()=>reservations.filter(r=>r.reservation_date===today),[reservations]);const people=todayReservations.reduce((a,r)=>a+(r.party_size||0),0)
 const changeReservation=async(id,status)=>{await supabase.from('pari_reservations').update({status}).eq('id',id);setReservations(x=>x.map(r=>r.id===id?{...r,status}:r))}
 const saveVenue=async()=>{const payload={name:edit.name,description:edit.description,address:edit.address,neighborhood:edit.neighborhood,phone:edit.phone,instagram_url:edit.instagram_url,auto_accept_reservations:!!edit.auto_accept_reservations};const {data,error}=await supabase.from('pari_venues').update(payload).eq('id',venue.id).select().single();if(error)return alert(error.message);setVenue(data);setEdit(data);alert('Cambios guardados')}
 const uploadMedia=async(file,type)=>{if(!file)return;const ext=file.name.split('.').pop();const path=`venues/${venue.id}/${type}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('pari-media').upload(path,file,{upsert:false});if(error)return alert(error.message);const {data:{publicUrl}}=supabase.storage.from('pari-media').getPublicUrl(path);if(type==='cover'){const {data}=await supabase.from('pari_venues').update({cover_url:publicUrl}).eq('id',venue.id).select().single();setVenue(data);setEdit(data)}else{const {data}=await supabase.from('pari_venue_photos').insert({venue_id:venue.id,image_url:publicUrl,position:photos.length}).select().single();setPhotos(x=>[...x,data])}}
 const deletePhoto=async p=>{await supabase.from('pari_venue_photos').delete().eq('id',p.id);setPhotos(x=>x.filter(i=>i.id!==p.id))}
 const createEvent=async()=>{if(!newEvent.title||!newEvent.starts_at)return;const {data,error}=await supabase.from('pari_events').insert({venue_id:venue.id,venue_name:venue.name,city:venue.city,title:newEvent.title,description:newEvent.description,starts_at:newEvent.starts_at,status:'published',type:'club_event'}).select().single();if(error)return alert(error.message);setEvents(x=>[...x,data]);setNewEvent({title:'',starts_at:'',description:''})}
 const deleteEvent=async id=>{await supabase.from('pari_events').delete().eq('id',id);setEvents(x=>x.filter(e=>e.id!==id))}
 const createPromo=async()=>{if(!newPromo.title)return;const {data,error}=await supabase.from('pari_venue_promotions').insert({venue_id:venue.id,title:newPromo.title,description:newPromo.description,is_active:true}).select().single();if(error)return alert(error.message);setPromos(x=>[data,...x]);setNewPromo({title:'',description:''})}
 if(loading)return <div className="loading-screen">Cargando Pari Negocios…</div>
 if(error)return <div className="login-page"><div className="login-card"><h1>Cuenta sin negocio</h1><div className="login-error"><AlertCircle/>{error}</div><button className="login-button" onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></div></div>
 const nav=[[BarChart3,'Resumen'],[Users,'Reservaciones'],[CalendarDays,'Eventos'],[Image,'Perfil del antro'],[Settings,'Configuración'],[ScanLine,'Check-in']]
 return <div className="layout"><aside><div className="brand">pari<span>.</span><small>NEGOCIOS</small></div><nav>{nav.map(([I,t])=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><I/>{t}</button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Cerrar sesión</button></aside><main><header><div><p>{venue?.name?.toUpperCase()} · {venue?.city?.toUpperCase()}</p><h1>{tab}</h1></div>{tab==='Eventos'&&<button onClick={()=>document.getElementById('newEvent')?.scrollIntoView()}><Plus/>Crear evento</button>}</header>
 {tab==='Resumen'&&<><section className="stats"><article><span>Reservaciones hoy</span><strong>{todayReservations.length}</strong><small>Datos en vivo</small></article><article><span>Personas esperadas</span><strong>{people}</strong><small>Para hoy</small></article><article><span>Próximos eventos</span><strong>{events.length}</strong><small>Publicados</small></article><article><span>Modo de reservas</span><strong>{venue.auto_accept_reservations?'Auto':'Manual'}</strong><small>Se cambia en Configuración</small></article></section><section className="panel"><h2>Reservaciones recientes</h2><ReservationTable rows={reservations.slice(0,8)} onChange={changeReservation}/></section></>}
 {tab==='Reservaciones'&&<section className="panel"><div className="panel-head"><div><h2>Todas las reservaciones</h2><p>Acepta o rechaza las pendientes cuando el modo sea manual.</p></div></div><ReservationTable rows={reservations} onChange={changeReservation}/></section>}
 {tab==='Eventos'&&<><section className="panel" id="newEvent"><h2>Crear evento</h2><div className="form-grid"><input placeholder="Nombre del evento" value={newEvent.title} onChange={e=>setNewEvent({...newEvent,title:e.target.value})}/><input type="datetime-local" value={newEvent.starts_at} onChange={e=>setNewEvent({...newEvent,starts_at:e.target.value})}/><textarea placeholder="Descripción" value={newEvent.description} onChange={e=>setNewEvent({...newEvent,description:e.target.value})}/><button onClick={createEvent}><PartyPopper/>Publicar evento</button></div></section><section className="panel"><h2>Eventos publicados</h2>{events.map(e=><div className="event-row" key={e.id}><div><b>{e.title}</b><span>{new Date(e.starts_at).toLocaleString('es-MX')}</span></div><button className="danger" onClick={()=>deleteEvent(e.id)}><Trash2/></button></div>)}</section></>}
 {tab==='Perfil del antro'&&<><section className="panel"><h2>Portada</h2>{venue.cover_url&&<img className="cover-preview" src={venue.cover_url}/>}<label className="upload-btn"><Upload/>Subir portada<input type="file" accept="image/*" hidden onChange={e=>uploadMedia(e.target.files?.[0],'cover')}/></label></section><section className="panel"><h2>Información</h2><div className="form-grid"><input value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="Nombre"/><textarea value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})} placeholder="Descripción"/><input value={edit.address||''} onChange={e=>setEdit({...edit,address:e.target.value})} placeholder="Dirección"/><input value={edit.neighborhood||''} onChange={e=>setEdit({...edit,neighborhood:e.target.value})} placeholder="Zona"/><input value={edit.phone||''} onChange={e=>setEdit({...edit,phone:e.target.value})} placeholder="Teléfono"/><input value={edit.instagram_url||''} onChange={e=>setEdit({...edit,instagram_url:e.target.value})} placeholder="Instagram"/><button onClick={saveVenue}><Save/>Guardar información</button></div></section><section className="panel"><div className="panel-head"><div><h2>Galería</h2><p>Estas imágenes aparecen en la página del antro.</p></div><label className="upload-btn"><Upload/>Agregar imagen<input type="file" accept="image/*" hidden onChange={e=>uploadMedia(e.target.files?.[0],'gallery')}/></label></div><div className="photo-grid">{photos.map(p=><div key={p.id}><img src={p.image_url}/><button onClick={()=>deletePhoto(p)}><Trash2/></button></div>)}</div></section><section className="panel"><h2>Promociones</h2><div className="form-grid"><input placeholder="Título" value={newPromo.title} onChange={e=>setNewPromo({...newPromo,title:e.target.value})}/><textarea placeholder="Descripción" value={newPromo.description} onChange={e=>setNewPromo({...newPromo,description:e.target.value})}/><button onClick={createPromo}><Plus/>Agregar promoción</button></div>{promos.map(p=><div className="event-row" key={p.id}><div><b>{p.title}</b><span>{p.description}</span></div></div>)}</section></>}
 {tab==='Configuración'&&<section className="panel settings-panel"><h2>Reservaciones</h2><button className="mode-toggle" onClick={()=>setEdit({...edit,auto_accept_reservations:!edit.auto_accept_reservations})}>{edit.auto_accept_reservations?<ToggleRight/>:<ToggleLeft/>}<div><b>{edit.auto_accept_reservations?'Confirmación automática':'Revisión manual'}</b><span>{edit.auto_accept_reservations?'Las nuevas reservaciones entran confirmadas.':'Las nuevas reservaciones quedan pendientes hasta que las aceptes.'}</span></div></button><button onClick={saveVenue}><Save/>Guardar configuración</button></section>}
 {tab==='Check-in'&&<section className="panel"><h2>Check-in</h2><p>Marca una reservación confirmada como llegada.</p>{reservations.filter(r=>r.status==='confirmed').map(r=><div className="event-row" key={r.id}><div><b>{r.party_size} personas · {r.reservation_date}</b><span>Reserva {r.id.slice(0,8).toUpperCase()}</span></div><button onClick={()=>changeReservation(r.id,'checked_in')}><Check/>Llegó</button></div>)}</section>}
 </main></div>
}
function ReservationTable({rows,onChange}){return <table><thead><tr><th>Reserva</th><th>Personas</th><th>Fecha</th><th>Hora</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.id.slice(0,8).toUpperCase()}</td><td>{r.party_size}</td><td>{r.reservation_date}</td><td>{String(r.arrival_time||'—').slice(0,5)}</td><td><span className={'status '+r.status}>{r.status}</span></td><td>{r.status==='pending'?<div className="row-actions"><button onClick={()=>onChange(r.id,'confirmed')}><Check/></button><button className="danger" onClick={()=>onChange(r.id,'rejected')}><X/></button></div>:'—'}</td></tr>):<tr><td colSpan="6" className="empty-row">Sin reservaciones.</td></tr>}</tbody></table>}
function App(){const [session,setSession]=useState(null);const [ready,setReady]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(!ready)return <div className="loading-screen">Cargando…</div>;return session?<Dashboard session={session}/>:<Login/>}
createRoot(document.getElementById('root')).render(<App/>)
